#!/bin/bash

if [ ! -e /portage/world ]
then
	cp -r /skel/portage/* /portage/
fi

[ -x /portage/first ] && /portage/first

while true
do
	/usr/local/bin/builder.sh
	inotifywait -e modify -r /portage
	sleep 30
done
